---
title: "Daniël Analysis"
output: html_document
---

```{r, messages=FALSE}
library(tidyverse)
```

# Organize and clean data

```{r}
#Read excel files in folder
files <- list.files(path = "responses", pattern = "\\.csv$")

#read in all separate data files into a single list
#gives warning that can be ignored (last line not empty)
datalist <- lapply(
  paste0("responses/", files), 
  function(x) suppressWarnings(read.table(x, header = F))
)

#determine max length to fill dataframe
max_length <- max(unlist(lapply(datalist,length)))

#fill dataframe
df_filled <- lapply(datalist,function(x) {
  ans <- rep(NA,length=max_length);
  ans[1:length(x)]<- x;
  return(ans)
})

colnamelist <- c("ID", "length", "judgement", "effect_size", "effect_size_direction", "true_mean1", "true_mean2", "obs_mean_1", "obs_mean2", "obs_mean_dif", "df", "tvalue", "pvalues", "obs_power", "d")

#combine lists into a dataframe, make numeric and rename columns
dat <- do.call(rbind, df_filled) %>%
  as.data.frame() %>%
  mutate_all(as.numeric) %>%
  rename_at(1:15, ~ colnamelist) %>%
  # deal with extra values on end of each line
  gather(key, val, 16:ncol(.)) %>%
  filter(!is.na(val)) %>%
  select(-key) %>%
  group_by_at(vars(one_of(colnamelist))) %>%
  nest()
```



## Create variables

```{r}
#create variable for correct/incorrect
#create variable for sig/nonsig

all_data <- dat %>%
  mutate(
    significant = ifelse(pvalues <= 0.05, 1, 0),
    judgement = recode(judgement, "0" = 0, "1" = 1, "2" = -1),
    right_answer = case_when( 
      (effect_size_direction == 0) ~ 0,
      (effect_size_direction > 0) ~ 1,
      (effect_size_direction < 0) ~ -1
    ),
    correct = ifelse(judgement == right_answer, 1, 0)
  )

#subset data ((note use of levels to deal with factor)) only trials with more than 5 responses
all_data_sub <- filter(all_data, length > 5)
```

```{r}
sub_pcnt <- all_data_sub %>%
  group_by(right_answer, effect_size_direction) %>%
  summarise(
    sig = mean(pvalues < .05) %>% round(2),
    z = mean(judgement == 0),
    p = mean(judgement == 1),
    n = mean(judgement == -1)
  ) %>%
  gather(judgement, pcnt, z:n) %>%
  mutate(
    judgement = recode(judgement, "z" = 0, "p" = 1, "n" = -1),
    pcnt = round(pcnt, 2),
    correct = right_answer == judgement
  )
```

## Plots

### Observed mean difference across conditions

```{r obs-mean-diff, fig.width = 8, fig.height = 5}
  ggplot() +
    geom_rect(data = sub_pcnt,
              aes(fill = correct),
              xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, 
              alpha = 0.3, show.legend = FALSE) +
    geom_vline(data = all_data_sub, aes(xintercept = effect_size_direction), color = "red") +
    geom_histogram(data = all_data_sub, aes(x=obs_mean_dif), 
                   binwidth = 0.1, color = "black", fill = "white") + 
    geom_text(data = sub_pcnt, aes(label = pcnt), x = -1.5, y = 25) +
    facet_grid(judgement~effect_size_direction) +
    theme_bw() +
    scale_fill_manual(values = c("white", "grey50"))

ggsave("obs_mean_diff.png", width = 16, height = 10)

```


# Calculate X% of data
```{r}

find_cover_region <- function(x, alpha=0.5) {
  n <- length(x)
  x <- sort(x)
  k <- as.integer(round((1-alpha) * n))
  i <- which.min(x[seq.int(n-k, n)] - x[seq_len(k+1L)])
  c(x[i], x[n-k+i-1L])
}
tapply(-all_data_sub$d, all_data_sub$judgement, find_cover_region)
tapply(all_data_sub$obs_mean_dif, all_data_sub$judgement, find_cover_region)
```


```{r fig-p, fig.width = 8, fig.height = 5}
ggplot() +
  geom_rect(data = sub_pcnt, aes(fill = correct),
              xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, 
              alpha = 0.3, show.legend = FALSE) +
  geom_histogram(data = all_data_sub, aes(x=pvalues),
                 binwidth = 0.05, boundary = 0, 
                 color = "black", fill = "white", alpha = 0.5) + 
  geom_text(data = sub_pcnt, aes(label = sig), x = .2, y = 50) +
  facet_grid(judgement ~ effect_size_direction) +
  theme_bw() +
  scale_fill_manual(values = c("white", "grey50"))

ggsave("power.png", width = 16, height = 10)
```

#mean power
```{r}
data <- group_by(all_data_sub, effect_size_direction, judgement)

summarize(data, power = mean(obs_power, na.rm = T))
summarize(data, mean_dif = mean(obs_mean_dif, na.rm = T))
summarize(data, d = mean(-d, na.rm = T)) #note -d because d in dataset is calculated in opposite diferection!

#Analyze p-values
data <- group_by(all_data_sub, effect_size_direction, judgement)
summarize(data, n = length(d), pvaluessig = sum(pvalues <= 0.05), pvalues_nonsig = sum(pvalues > 0.05), power = sum(pvalues <= 0.05)/(sum(pvalues > 0.05) + sum(pvalues <= 0.05))*100, mean_dif = mean(obs_mean_dif, na.rm = T), obs_power = mean(obs_power, na.rm = T))

```

